# Generated by Django 5.2.8 on 2025-12-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABANDONED", "Abandoned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
