# Generated by Django 5.2.8 on 2025-12-10 01:59

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_producttype_is_digital_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="seo_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Override defaults. Keys: title, description, robots, etc.",
                verbose_name="SEO Overrides",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="seo_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Override defaults. Keys: title, description, robots, etc.",
                verbose_name="SEO Overrides",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Override defaults. Keys: title, description, robots, etc.",
                verbose_name="SEO Overrides",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                upload_to=products.models.product_thumbnail_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(upload_to=products.models.variant_image_upload_to),
        ),
    ]
